spring.application.name=account-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
server.port=8761
management.health.eureka.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
