spring.application.name=microservicesexe2
server.port=8080

# 1?? EdgeService Route
spring.cloud.gateway.routes[0].id=edge_route
spring.cloud.gateway.routes[0].uri=https://httpbin.org
spring.cloud.gateway.routes[0].predicates[0]=Path=/edge/**

# 2?? LoadBalanced Route
spring.cloud.gateway.routes[1].id=load_balanced_route
spring.cloud.gateway.routes[1].uri=lb://example-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/loadbalanced/**

# 3?? Resilience / CircuitBreaker Route
spring.cloud.gateway.routes[2].id=cb_route
spring.cloud.gateway.routes[2].uri=http://localhost:9090/failure
spring.cloud.gateway.routes[2].predicates[0]=Path=/cbtest/**
spring.cloud.gateway.routes[2].filters[0]=CircuitBreaker=exampleCircuitBreaker,fallbackUri=forward:/fallback

# Resilience4J Circuit Breaker Config
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.slidingWindowSize=5
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.failureRateThreshold=50
